version: "3.9"

# services:
#   db:
#     image: pgvector/pgvector:pg16
#     container_name: enterprise_pgvector
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: enterprise_bot
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

  services:
  db:
    image: pgvector/pgvector:pg16
    container_name: enterprise_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enterprise_bot
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: enterprise_backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

volumes:
  pgdata: